version: "3.7"

services:
  db:
    container_name: ${PROJECT_NAME}_DB
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    restart: always

  web: &web
    container_name: ${PROJECT_NAME}_backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:${BACKEND_PORT}
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./:/app
      - ./static:/home/app/web/static
      - ./media:/home/app/web/media
      - ./locale:/home/app/web/locale
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
      - redis

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:6-alpine
    restart: always

#  celery:
#    container_name: ${PROJECT_NAME}_celery
#    <<: *web
#    ports: [ ]
#    command: celery -A core worker --beat --scheduler django --loglevel=info
#    restart: always

volumes:
  postgres_data:
  static_volume:
