# Generated by Django 5.0.3 on 2024-03-09 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_productrawmaterial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='unit',
            field=models.CharField(choices=[('m', 'Meter'), ('m2', 'Square Meter'), ('kg', 'Kilogram'), ('pcs', 'Piece')], max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='productrawmaterial',
            name='unit',
            field=models.CharField(blank=True, choices=[('m', 'Meter'), ('m2', 'Square Meter'), ('kg', 'Kilogram'), ('pcs', 'Piece')], max_length=10, null=True, verbose_name='Unit'),
        ),
        migrations.CreateModel(
            name='WarehouseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('remainder', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remainder')),
                ('unit', models.CharField(blank=True, choices=[('m', 'Meter'), ('m2', 'Square Meter'), ('kg', 'Kilogram'), ('pcs', 'Piece')], max_length=10, null=True, verbose_name='Unit')),
                ('price', models.FloatField(verbose_name='Price')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='warehouse.rawmaterial')),
            ],
            options={
                'verbose_name': 'Warehouse Batch',
                'verbose_name_plural': 'Warehouse Batches',
            },
        ),
    ]
