# Generated by Django 5.0.3 on 2024-03-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemRawMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, choices=[('m', 'Meter'), ('m2', 'Square Meter'), ('kg', 'Kilogram'), ('pcs', 'Piece')], max_length=10, null=True, verbose_name='Unit')),
                ('price', models.FloatField(null=True, verbose_name='Price')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_materials', to='warehouse.orderitem')),
                ('raw_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='warehouse.rawmaterial')),
                ('warehouse_batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='warehouse.warehousebatch')),
            ],
            options={
                'verbose_name': 'Order Item Raw Material',
                'verbose_name_plural': 'Order Item Raw Materials',
            },
        ),
    ]
